<?php $this->headMeta()->setName('description',DESC);?>
<?php foreach($this->prods as $val):?>
 <div class="prods_part">
  <div class="prods_part_caption"><h1 style="color:<?php echo $val['color'];?>"><?php echo $val['part'];?></h1></div>
  <ul class="prods_items_list">
   <?php foreach($val['prods'] as $val2):?>
    <li>
     <?php $url = $this->url(array('controller'=>'products','action'=>'getdetails','item'=>$val2['translit']),null,true);?>
     <?php $pic = ($val2['picture']==''?'/images/nopic.png':$val2['picture']);?>
     <div class="prod_name"><h2><a href="<?php echo $url;?>" title="<?php echo glob_quoteStr($val2['name']);?>"><?php echo $val2['name']?></a></h2></div>
     <div class="prod_info">
      <div class="prod_img left"><span class="r" r="<?php echo $url;?>"><img width="80" onload="resizeme($(this));" alt="<?php echo glob_quoteStr($val2['name']);?>" src="<?php echo $pic;?>"></span></div>
      <div class="prod_details left">
       <?php echo glob_productInfoFormat('Автор:',$val2['author']);?>
       <?php echo glob_productInfoFormat('Производитель:',$val2['producer']);?>
       <?php echo glob_productInfoFormat('Серия:',$val2['series']);?>
       <?php echo glob_productInfoFormat('Год:',$val2['year']);?>
       <?php echo glob_productInfoFormat('Переплет:',$val2['cover']);?>
       <?php echo glob_productInfoFormat('Страниц:',$val2['pages']);?>
      </div>
      <div class="clear"></div>
     </div>
     <div class="prod_price_c">
      <div class="prod_price2 left"><?php echo $val2['price']." руб.";?></div>
      <div class="btnBuy_d left"><button class="btnBuy" onclick="<?php echo 'buyFromCat('.$val2['id'].',$(this))';?>">Купить</button></div>
      <input type="hidden" class="holdprodid" value="<?php echo $val2['id'];?>">
      <div class="clear"></div>
     </div>
    </li>
   <?php endforeach;?>
  </ul>
  <iframe name="cartdetailframe" id="cartdetailframe" frameborder="no" width="0" height="0" src="<?php echo DOMAIN_PATH.'/application/views/scripts/cartFrame.html';?>">
  </iframe>
 </div>
<?php endforeach;?>